# Generated by Django 5.1.1 on 2024-09-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rent_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('crime_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('foreign_population_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('infrastructure_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
