# Generated by Django 5.1.1 on 2024-11-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('minimum_rent', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geometry_coordinates', models.JSONField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_crimes', models.IntegerField()),
                ('robbery', models.IntegerField()),
                ('total_assaults', models.IntegerField()),
                ('total_thefts', models.IntegerField()),
                ('total_residential_burglary', models.IntegerField()),
                ('total_arson_incidents', models.IntegerField()),
                ('total_vandalism', models.IntegerField()),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.borough')),
            ],
        ),
        migrations.AddField(
            model_name='borough',
            name='lifestyles',
            field=models.ManyToManyField(blank=True, to='neighborhoods.lifestyle'),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.borough')),
            ],
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_friendly_percentage', models.FloatField()),
                ('foreign_residents_percentage', models.FloatField()),
                ('median_income', models.FloatField()),
                ('age_distribution', models.JSONField()),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='RentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('avg_size', models.FloatField()),
                ('min_size', models.FloatField()),
                ('max_size', models.FloatField()),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.borough')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.neighborhood')),
            ],
        ),
    ]
