# Generated by Django 5.1.1 on 2024-11-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('minimum_rent', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geometry_coordinates', models.JSONField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_crimes', models.IntegerField()),
                ('robbery', models.IntegerField()),
                ('total_assaults', models.IntegerField()),
                ('total_thefts', models.IntegerField()),
                ('total_residential_burglary', models.IntegerField()),
                ('total_arson_incidents', models.IntegerField()),
                ('total_vandalism', models.IntegerField()),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.borough')),
            ],
        ),
        migrations.AddField(
            model_name='borough',
            name='lifestyles',
            field=models.ManyToManyField(blank=True, to='neighborhoods.lifestyle'),
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.borough')),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.borough')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Demographics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('germans', models.IntegerField()),
                ('foreigners', models.IntegerField()),
                ('under_6', models.IntegerField()),
                ('six_to_15', models.IntegerField()),
                ('fifteen_to_18', models.IntegerField()),
                ('eighteen_to_27', models.IntegerField()),
                ('twenty_seven_to_45', models.IntegerField()),
                ('forty_five_to_55', models.IntegerField()),
                ('fifty_five_and_more', models.IntegerField()),
                ('eu', models.IntegerField()),
                ('france', models.IntegerField()),
                ('italy', models.IntegerField()),
                ('spain', models.IntegerField()),
                ('poland', models.IntegerField()),
                ('greece', models.IntegerField()),
                ('austria', models.IntegerField()),
                ('romania', models.IntegerField()),
                ('united_kingdom', models.IntegerField()),
                ('former_yougoslavia', models.IntegerField()),
                ('former_soviet_union', models.IntegerField()),
                ('russia', models.IntegerField()),
                ('ukraine', models.IntegerField()),
                ('islamic_countries', models.IntegerField()),
                ('turkey', models.IntegerField()),
                ('iran', models.IntegerField()),
                ('arab_countries_inc_syria', models.IntegerField()),
                ('lebanon', models.IntegerField()),
                ('syria', models.IntegerField()),
                ('vietnam', models.IntegerField()),
                ('usa', models.IntegerField()),
                ('not_clearly_assignable', models.IntegerField()),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.borough')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Nightlife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.borough')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.borough')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='RentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_price', models.FloatField()),
                ('min_price', models.FloatField()),
                ('max_price', models.FloatField()),
                ('avg_size', models.FloatField()),
                ('min_size', models.FloatField()),
                ('max_size', models.FloatField()),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.borough')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.borough')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.neighborhood')),
            ],
        ),
    ]
