# Generated by Django 5.1.1 on 2024-09-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='borough',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='borough',
            name='lifestyles',
        ),
        migrations.AddField(
            model_name='borough',
            name='lifestyles',
            field=models.ManyToManyField(blank=True, to='neighborhoods.lifestyle'),
        ),
    ]
