# Generated by Django 5.1.1 on 2024-11-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='coat_of_arms_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
