# Generated by Django 5.1.1 on 2024-11-25 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hospital',
            new_name='Transports',
        ),
        migrations.RemoveField(
            model_name='park',
            name='borough',
        ),
        migrations.RemoveField(
            model_name='park',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='school',
            name='borough',
        ),
        migrations.RemoveField(
            model_name='school',
            name='neighborhood',
        ),
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.borough')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighborhoods.neighborhood')),
            ],
        ),
        migrations.DeleteModel(
            name='Nightlife',
        ),
        migrations.DeleteModel(
            name='Park',
        ),
        migrations.DeleteModel(
            name='School',
        ),
    ]
