# Generated by Django 5.1.1 on 2024-11-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0002_borough_coat_of_arms_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borough',
            name='coat_of_arms_image',
        ),
    ]
