# Generated by Django 5.1.1 on 2024-09-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0004_amenity_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
