# Generated by Django 5.1.1 on 2024-11-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0002_rename_hospital_transports_remove_park_borough_and_more'),
        ('neighborhoods', '0004_cultural'),
    ]

    operations = [
    ]
