# Generated by Django 5.1.1 on 2024-11-26 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0005_merge_20241126_0838'),
        ('neighborhoods', '0005_merge_20241126_0842'),
    ]

    operations = [
    ]
