# Generated by Django 5.1.1 on 2024-11-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0006_merge_20241126_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='borough',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cultural',
        ),
    ]
