# Generated by Django 5.1.1 on 2024-12-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoods', '0007_borough_description_delete_cultural'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
